Add more options (802.11r & disable IPv6)
imp1sh/ansible_openwrt pull request #5
Opened 2022-08-07 16:54 UTC by PhilipWhiteside

I needed a few more options that I didn't see in the collection. I have added the following:

- [All options listed for 802.11r](https://openwrt.org/docs/guide-user/network/wifi/basic#fast_bss_transition_options_80211r)
- [Single 'ipv6' option to disable IPv6 on an interface](https://openwrt.org/docs/guide-user/base-system/basic-networking#options_valid_for_all_protocol_types)

Options are strings directly copied from the linked documentation.

2022-08-08 22:28 UTC, imp1sh reviewed
This is better

2022-08-08 22:32 UTC, imp1sh reviewed
This is better

2022-08-08 22:48 UTC, imp1sh requested changes
plz adjust like this.

2022-08-08 22:54 UTC, imp1sh reviewed
This looks ok.

2022-08-08 22:56 UTC, imp1sh approved these changes

2022-08-17 09:28 UTC, imp1sh commented
Hi Philip,
the single option for IPv6 I cannot merge, because it conflicts with the original ipv6 statement above your line.
I tried to suggest how it needed to be changed with the help of the builtin github editor but it doesn't seem to have worked.
Yet I would like to merge your 802.11r changes, yet I just don't know how.

2022-08-19 07:57 UTC, closed without merging

2022-08-19 08:04 UTC, PhilipWhiteside commented
Hey, I couldn't figure it out either, I'm more used to GitLab. I created a new PR with just the 802.11r options #6